[package]
name = "items_tools"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }
rand = { workspace = true }

engine = { path = "../engine" }
util = { path = "../util" }
actors = { path = "../actors" }
world = { path = "../world" }
interfaces = { path = "../interfaces" }
physics = { path = "../physics" }
items = { path = "../items" }

[lints]
workspace = true
