#!/bin/bash
# generated by claude
set -e

# Configuration
REPO_ROOT=$(git rev-parse --show-toplevel)
RELEASE_DIR="$HOME/coding/rust/Wisphaven Releases"
ASSETS_DIR="$REPO_ROOT/assets"
CURRENT_DATE=$(date +"%Y-%m-%d")

# Target configurations
declare -A TARGETS=(
  ["windows"]="x86_64-pc-windows-gnu"
  ["linux"]="x86_64-unknown-linux-gnu"
  # ["mac-intel"]="x86_64-apple-darwin"
  # ["mac-silicon"]="aarch64-apple-darwin"
)

declare -A EXECUTABLES=(
  ["windows"]="wisphaven.exe"
  ["linux"]="wisphaven"
  # ["mac-intel"]="wisphaven"
  # ["mac-silicon"]="wisphaven"
)

# Function to get the current version from git tags
get_current_version() {
  git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0"
}

# Function to bump version
bump_version() {
  local current_version=$(get_current_version | sed 's/^v//')
  local bump_type=$1

  IFS='.' read -r major minor patch <<< "$current_version"

  case "$bump_type" in
    "major")
      major=$((major + 1))
      minor=0
      patch=0
      ;;
    "minor")
      minor=$((minor + 1))
      patch=0
      ;;
    "patch")
      patch=$((patch + 1))
      ;;
    *)
      echo "Invalid bump type. Use 'major', 'minor', or 'patch'."
      exit 1
      ;;
  esac

  echo "v$major.$minor.$patch"
}

# Function to update version in Cargo.toml
update_cargo_toml() {
  local new_version=$1
  local version_without_v=${new_version#v}

  # Update version in main Cargo.toml
  sed -i.bak "s/^version = \".*\"/version = \"$version_without_v\"/" "$REPO_ROOT/Cargo.toml"
  rm "$REPO_ROOT/Cargo.toml.bak"

  # Commit the version change
  git add "$REPO_ROOT/Cargo.toml"
  git commit -m "Bump version to $new_version"
  git tag "$new_version"

  echo "Updated Cargo.toml to version $new_version"
}

# Function to compile for all targets
compile_targets() {
  echo "Compiling for all targets..."
  for target_name in "${!TARGETS[@]}"; do
    local target_triple="${TARGETS[$target_name]}"
    echo "Compiling for $target_name ($target_triple)..."
    cargo build --release --target "$target_triple"
  done
}

# Function to create release directory structure
create_release_dirs() {
  local version=$1
  local release_name="$version-$CURRENT_DATE"
  local release_path="$RELEASE_DIR/$release_name"

  mkdir -p "$release_path"

  for target_name in "${!TARGETS[@]}"; do
    mkdir -p "$release_path/$target_name"
  done

  echo "$release_path"
}

# Function to copy executables and assets
copy_files() {
  local release_path=$1

  for target_name in "${!TARGETS[@]}"; do
    local target_triple="${TARGETS[$target_name]}"
    local executable="${EXECUTABLES[$target_name]}"
    local target_dir="$release_path/$target_name"

    # Copy executable
    cp "$REPO_ROOT/target/$target_triple/release/$executable" "$target_dir/"

    # Copy assets
    cp -r "$ASSETS_DIR" "$target_dir/"

    echo "Copied files for $target_name"
  done
}

# Function to create zip archives
create_zips() {
  local release_path=$1
  local version=$2

  for target_name in "${!TARGETS[@]}"; do
    local target_dir="$release_path/$target_name"
    local zip_name="$release_path/wisphaven-$version-$target_name.zip"

    (cd "$target_dir" && zip -r "$zip_name" .)

    echo "Created zip for $target_name: $zip_name"
  done
}

# Function to create release notes template
create_release_notes() {
  local release_path=$1
  local template_content="## What's Changed\n- "

  echo -e "$template_content" > "$release_path/release-notes.md"
  echo "Created release notes template at $release_path/release-notes.md"
}

# Main function
main() {
  if [ $# -ne 1 ]; then
    echo "Usage: $0 <major|minor|patch>"
    exit 1
  fi

  local bump_type=$1
  local new_version=$(bump_version "$bump_type")

  echo "Preparing release $new_version"

  # Update version in Cargo.toml
  update_cargo_toml "$new_version"

  # Compile for all targets
  compile_targets

  # Create release directory structure
  local release_path=$(create_release_dirs "$new_version")

  # Copy executables and assets
  copy_files "$release_path"

  # Create zip archives
  create_zips "$release_path" "$new_version"

  # Create release notes template
  create_release_notes "$release_path"

  echo "Release $new_version completed successfully!"
  echo "Release files are available at: $release_path"
}

main "$@"
