[package]
name = "json_effects"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { workspace = true }

interfaces = { path = "../interfaces" }
json_interop = { path = "../json_interop" }
engine = { path = "../engine" }
items = { path = "../items" }
quests = { path = "../quests" }

[lints]
workspace = true
