[package]
name = "blocks"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }

util = { path = "../util" }
actors = { path = "../actors" }
world = { path = "../world" }
interfaces = { path = "../interfaces" }

[lints]
workspace = true
